Text = {
    ['ES'] = {
        -- UI
        GarageName = "Nombre del Garaje",
        GarageCreateSpan = "Nombre único por garaje",
        GarageJob = "Trabajo",
        GarageJobSpan = "Si no escribes nada, será para todos.",
        GarageType = "Tipo de Garaje",
        GarageTypeSpan = "Tipo de garaje, 2 opciones: garaje o depósito",
        GarageType1 = "Garaje",
        GarageType2 = "Depósito",
        GarageImpound = "Precio del Depósito",
        GarageImpoundSpan = "Establece un precio predeterminado para recuperar vehículos de este depósito.",
        GarageSociety = "Sociedad",
        GarageSocietySpan = "Nombre de la sociedad a la que irán los fondos recaudados.",
        GarageActionType = "Tipo de de Zona",
        GarageActionTypeSpan = "TextUi / Target",
        GarageActionType1 = "Target",
        GarageActionType2 = "TextUI",
        GarageNPC = "NPC Hash",
        GarageNPCSpan = "Agrega un NPC a la zona objetivo, funciona con las coordenadas del garaje.",
        GarageVehicleType = "Tipo de Vehículo",
        GarageVehicleTypeSpan = "Selecciona las categorías de vehículos que se pueden estacionar.",
        GarageDebug = "Debug",
        GarageDebugSpan = "Visualizar la zona",
        GarageInTocar = "Dentro del Vehículo",
        GarageInTocarSpan = "Colocar al jugador en el vehículo al spawnear el vehículo",
        GarageBlip = "Blip",
        GarageBlipSpan = "Ocultar / mostrar BLIP del garaje",
        GarageCustomCars = "Vehículos Personalizados",
        GarageCustomCarsSpan =  "Establece una lista de vehículos predeterminados, solo los vehículos generados desde este garaje pueden ser guardados.",
        GarageRentACar = "Alquilar un Vehículo",
        GarageRentACarSpan = "Establecer precio para alquilar un vehículo",
        GarageSharedVehicles = "Garaje Mixto",
        GarageSharedVehiclesSpan = "Ver todo los vehículos en propiedad del jugador.",
        GarageDefaultImpound = "Default impound",
        GarageDefaultImpoundSpan = "Establecer un garage 'impound' para recuperar el vehiculo",
        GaragePayMethod = "Metodo de pago",
        GaragePayMethodMoney = "Efectivo",
        GaragePayMethodBank = "Cuenta bancaria",
        GarageButton1 = "Coords",
        GarageButton2 = "Set Zone",
        GarageButton3 = "Spawn Coords",
        GarageButton4 = "Crear Garage",
        GarageButton5 = "Teleport",
        GarageButton6 = "Update",
        GarageButton7 = "Borrar",
        GarageButton8 = "Lista de garages",
        GarageMenu1 = "Precio:",
        GarageMenu2 = "Fecha:",
        GarageMenu3 = "Pagar y recuperar",
        GarageMenu4 = "Kilometros",
        GarageMenu5 = "Retirar",
        GarageMenu6 = "Llaves",
        GarageMenu7 = "GPS",
        GarageMenu9 = "Gasolina",
        GarageMenu10 = "Motor",
        GarageMenu11 = "Carroceria",
        GarageMenu12 = "GPS",


        --Notifications
        notYourVehicle = 'Este vehículo no es tuyo...',
        impound1 = '¡Has pagado %s$ por tu vehículo!',
        impound2 = 'No tienes suficiente dinero para recuperar tu vehículo',
        impound3 = '',
        noSpawnPos = 'No hay punto de aparición',
        setBlip = 'Vehículo marcado en el mapa',
        noVehicles = 'No tienes ningun vehículo en el garaje.',

        --Target
        TargetSaveCar = 'Depositar vehículo',
        TargetImpound = 'Enviar al Deposito',

        -- Impound
        ImpoundOption1 = 'Incautar vehículo',
        ImpoundOption2 = 'Razon',
        ImpoundOption3 = 'Precio',

        --Admin Zone
        GarageCreate1 = 'mGarage CREATE',
        GarageCreate2 = 'mGarage DELETE',
        GarageCreate3 = 'mGarage UPDATE',
        GarageCreate4 = 'Nombre [ %s ] para garaje duplicado.',
        GarageCreate5 = 'Garaje %s Creado correctamente',
        GarageCreate6 = 'Garaje eliminado correctamente',
        GarageCreate7 = 'Garaje actualizado correctamente',
        TextUiCreateZone = '[MB1] + Punto   \n  [MB2] Eliminar ultimo punto   \n  [SCROLL] Altura  \n  [ENTER] Guardar Zona  \n  [BACKSPACE] Cerrar ',
        TextUiCoords = '[E] +Coords  \n  [SCROLL] Direccion  \n  [BACKSPACE] Eliminar ultima coord  \n  [G] Nada/Player/Vehículo  \n  [ENTER] Guardar Coords'
    },
    ['EN'] = {
        -- UI
        GarageName = "Garage Name",
        GarageCreateSpan = "Unique name per garage",
        GarageJob = "Job",
        GarageJobSpan = "If left blank, it will be for everyone.",
        GarageType = "Garage Type",
        GarageTypeSpan = "Garage type, 2 options: garage or impound",
        GarageType1 = "Garage",
        GarageType2 = "Impound",
        GarageImpound = "Impound Price",
        GarageImpoundSpan = "Set a default price to retrieve vehicles from this impound.",
        GarageSociety = "Society",
        GarageSocietySpan = "Name of the society where funds will go.",
        GarageActionType = "Zone Type",
        GarageActionTypeSpan = "TextUI / Target",
        GarageActionType1 = "Target",
        GarageActionType2 = "TextUI",
        GarageNPC = "NPC Hash",
        GarageNPCSpan = "Add an NPC to the target zone, works with garage coordinates.",
        GarageVehicleType = "Vehicle Type",
        GarageVehicleTypeSpan = "Select vehicle categories that can be parked.",
        GarageDebug = "Debug",
        GarageDebugSpan = "Visualize the zone",
        GarageInTocar = "Inside the Vehicle",
        GarageInTocarSpan = "Place the player in the vehicle when spawning the vehicle",
        GarageBlip = "Blip",
        GarageBlipSpan = "Hide / show garage BLIP",
        GarageCustomCars = "Custom Vehicles",
        GarageCustomCarsSpan =  "Set a list of default vehicles, only vehicles spawned from this garage can be saved.",
        GarageRentACar = "Rent a Vehicle",
        GarageRentACarSpan = "Set price to rent a vehicle",
        GarageSharedVehicles = "Mixed Garage",
        GarageSharedVehiclesSpan = "View all vehicles owned by the player.",
        GarageDefaultImpound = "Default impound",
        GarageDefaultImpoundSpan = "Set an 'impound' garage to retrieve the vehicle",
        GaragePayMethod = "Payment Method",
        GaragePayMethodMoney = "Cash",
        GaragePayMethodBank = "Bank Account",
        GarageButton1 = "Coords",
        GarageButton2 = "Set Zone",
        GarageButton3 = "Spawn Coords",
        GarageButton4 = "Create Garage",
        GarageButton5 = "Teleport",
        GarageButton6 = "Update",
        GarageButton7 = "Delete",
        GarageButton8 = "Garages List",
        GarageMenu1 = "Price:",
        GarageMenu2 = "Date:",
        GarageMenu3 = "Pay and retrieve",
        GarageMenu4 = "Mileage",
        GarageMenu5 = "Retrieve",
        GarageMenu6 = "Keys",
        GarageMenu7 = "GPS",
        GarageMenu9 = "Gasoline",
        GarageMenu10 = "Engine",
        GarageMenu11 = "Body",
        GarageMenu12 = "GPS",

        -- Notifications
        notYourVehicle = 'This vehicle is not yours...',
        impound1 = 'You\'ve paid %s$ for your vehicle!',
        impound2 = 'You don\'t have enough money to retrieve your vehicle.',
        impound3 = '',
        noSpawnPos = 'No spawn point available',
        setBlip = 'Vehicle marked on the map',
        noVehicles = 'You don\'t have any vehicles in the garage.',

        --Target
        TargetSaveCar = 'Deposit vehicle',
        TargetImpound = 'Send to Impound',

        -- Impound
        ImpoundOption1 = 'Impound vehicle',
        ImpoundOption2 = 'Reason',
        ImpoundOption3 = 'Price',

        --Admin Zone
        GarageCreate1 = 'mGarage CREATE',
        GarageCreate2 = 'mGarage DELETE',
        GarageCreate3 = 'mGarage UPDATE',
        GarageCreate4 = 'Name [ %s ] for duplicated garage.',
        GarageCreate5 = 'Garage %s Created successfully',
        GarageCreate6 = 'Garage deleted successfully',
        GarageCreate7 = 'Garage updated successfully',
        TextUiCreateZone = '[MB1] + Point   \n  [MB2] Delete last point   \n  [SCROLL] Height  \n  [ENTER] Save Zone  \n  [BACKSPACE] Close ',
        TextUiCoords = '[E] +Coords  \n  [SCROLL] Direction  \n  [BACKSPACE] Delete last coord  \n  [G] None/Player/Vehicle  \n  [ENTER] Save Coords'
    }
}
