Text = {
    ['ES'] = {
        -- UI
        GarageName = "Nombre del Garaje",
        GarageCreateSpan = "Nombre único por garaje",
        GarageJob = "Trabajo",
        GarageJobSpan = "Si no escribes nada, será para todos.",
        GarageType = "Tipo de Garaje",
        GarageTypeSpan = "Tipo de garaje, 2 opciones: garaje o depósito",
        GarageType1 = "Garaje",
        GarageType2 = "Depósito",
        GarageImpound = "Precio del Depósito",
        GarageImpoundSpan = "Establece un precio predeterminado para recuperar vehículos de este depósito.",
        GarageSociety = "Sociedad",
        GarageSocietySpan = "Nombre de la sociedad a la que irán los fondos recaudados.",
        GarageActionType = "Tipo de de Zona",
        GarageActionTypeSpan = "TextUi / Target",
        GarageActionType1 = "Target",
        GarageActionType2 = "TextUI",
        GarageNPC = "NPC Hash",
        GarageNPCSpan = "Agrega un NPC a la zona objetivo, funciona con las coordenadas del garaje.",
        GarageVehicleType = "Tipo de Vehículo",
        GarageVehicleTypeSpan = "Selecciona las categorías de vehículos que se pueden estacionar.",
        GarageDebug = "Debug",
        GarageDebugSpan = "Visualizar la zona",
        GarageInTocar = "Dentro del Vehículo",
        GarageInTocarSpan = "Colocar al jugador en el vehículo al spawnear el vehículo",
        GarageBlip = "Blip",
        GarageBlipSpan = "Ocultar / mostrar BLIP del garaje",
        GarageCustomCars = "Vehículos Personalizados",
        GarageCustomCarsSpan = "Establece una lista de vehículos predeterminados, solo los vehículos generados desde este garaje pueden ser guardados.",
        GarageRentACar = "Alquilar un Vehículo",
        GarageRentACarSpan = "Establecer precio para alquilar un vehículo",
        GarageSharedVehicles = "Garaje Mixto",
        GarageSharedVehiclesSpan = "Ver todo los vehículos en propiedad del jugador. (No esta completo)",
       
        --Notifications
        notYourVehicle = 'Este vehículo no es tuyo...',
        impound1 = '¡Has pagado %s$ por tu vehículo!',
        impound2 = 'No tienes suficiente dinero para recuperar tu vehículo',
        impound3 = '',
        noSpawnPos = 'No hay punto de aparición',
        setBlip = 'Vehículo marcado en el mapa',

        --Target
        TargetSaveCar = 'Depositar vehículo',
        TargetImpound = 'Enviar al Deposito',

        -- Impound
        ImpoundOption1 = 'Incautar vehículo',
        ImpoundOption2 = 'Razon',
        ImpoundOption3 = 'Precio',
    },
    ['EN'] = {
        -- User Interface
        GarageName = "Garage Name",
        GarageCreateSpan = "Unique name per garage",
        GarageJob = "Job",
        GarageJobSpan = "If left blank, it will be for everyone.",
        GarageType = "Garage Type",
        GarageTypeSpan = "Garage type, 2 options: garage or impound",
        GarageType1 = "Garage",
        GarageType2 = "Impound",
        GarageImpound = "Impound Price",
        GarageImpoundSpan = "Set a default price to retrieve vehicles from this impound.",
        GarageSociety = "Society",
        GarageSocietySpan = "Name of the society where funds will go.",
        GarageActionType = "Zone Type",
        GarageActionTypeSpan = "TextUI / Target",
        GarageActionType1 = "Target",
        GarageActionType2 = "TextUI",
        GarageNPC = "NPC Hash",
        GarageNPCSpan = "Add an NPC to the target zone, works with garage coordinates.",
        GarageVehicleType = "Vehicle Type",
        GarageVehicleTypeSpan = "Select vehicle categories that can be parked.",
        GarageDebug = "Debug",
        GarageDebugSpan = "Visualize the zone",
        GarageInVehicle = "Inside the Vehicle",
        GarageInVehicleSpan = "Place the player in the vehicle when spawning the vehicle",
        GarageBlip = "Blip",
        GarageBlipSpan = "Hide / show garage BLIP",
        GarageCustomCars = "Custom Vehicles",
        GarageCustomCarsSpan = "Set a list of default vehicles, only vehicles spawned from this garage can be saved.",
        GarageRentACar = "Rent a Vehicle",
        GarageRentACarSpan = "Set price to rent a vehicle",
        GarageSharedVehicles = "Mixed Garage",
        GarageSharedVehiclesSpan = "View all vehicles owned by the player. (Not complete)",
       
        -- Notifications
        notYourVehicle = "This vehicle is not yours...",
        impound1 = "You've paid %s$ for your vehicle!",
        impound2 = "You don't have enough money to retrieve your vehicle.",
        impound3 = "",
        noSpawnPos = "No spawn point available",
        setBlip = "Vehicle marked on the map",

        -- Target
        TargetSaveCar = "Deposit vehicle",
        TargetImpound = "Send to Impound",

        -- Impound
        ImpoundOption1 = "Impound vehicle",
        ImpoundOption2 = "Reason",
        ImpoundOption3 = "Price",
    }
}
